[package]
name = "zmake"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.51", features = ["derive","cargo","unicode","wrap_help"] }
semver = "1.0.27"
unicode-ident = "1.0.22"
thiserror = "2"
shadow-rs = "1.4"
clap_complete = "4.5.51"

[build-dependencies]
shadow-rs = "1.4"
clap_complete = "4.5.51"
clap = { version = "4.5.51", features = ["derive","cargo","unicode","wrap_help"] }
